### ISSUE TITLE
Tag Docker images

### ISSUE THREAD

**Issue by bsideup** [dperson/nginx#1]
Hi!

Could you please tag & version Docker images? 

https://github.com/dperson/nginx/commit/bf19dec3abb1b16e7937ae776a638089d2adabd4

This commit broke our app because we relied on this files :)

**Comment by dperson** [comment]
Yes, that's a good idea. Apologies for the breakage. I should have thought that through more fully. Left it in a branch till the next day, instead of committing it in the middle of the night. I'll make another update, so that it  will work with both the original names and the naming convention of letsencrypt.org.

**Comment by bsideup** [comment]
@dperson awesome, thanks :) 

FYI your image is being used for testing our tool called Configo:

https://github.com/zeroturnaround/configo/blob/master/spec/integration/sources/http.bats

Thanks for it :)

**Comment by dperson** [comment]
I just pushed the update. Docker hub is building it now. Hope that it didn't waste too much of your time. I'm glad that it's been working for you.
