### ISSUE TITLE
ARMHF

### ISSUE THREAD

**Issue by barrtailor** [dperson/nginx#19]
I have been testing your openvpn-client on one of my odroids and would like to use your nginx container as well. Didn't see an armhf tagged build of nginx for your container  at dockerhub, and was wondering if there's anything that could be done to make such a container. Thanks in advance for the consideration as well as for your other great work.

**Comment by dperson** [comment]
It's a bit different as my other containers are built on alpine, but nginx doesn't provide new builds for it. So this container has stayed based on debian. I'll see what I can do, but haven't had much time, I'm changing jobs and moving...

**Comment by barrtailor** [comment]
Completely understandable...I appreciate you considering it! Best of luck with the IRL stuff :)

**Comment by whi4** [comment]
Hi,
I cannot find debian stretch docker version for armhf.  I can find debian jessie, but this does not build properly because the gnupg1 lib is not available (according to the error messages).

I wonder if you could please put up an old Dockerfile built with debian jessie?

Thanks very much.

Regards,  Robert

**Comment by dperson** [comment]
@barrtailor sorry, I really don't have time to build/maintain a second version.

@whi4 it's in the github repo.
