### ISSUE TITLE
Usage of the new proxy hosts parameters

### ISSUE THREAD

**Issue by TelegraphAbsenceMan** [dperson/nginx#31]
Big fan of this image, I've been using it for some time!

In order to clean up my URLs, I was playing with the new proxy host parameter and I've run into some issues:

Maybe I'm misunderstanding the purpose, but if I am using it e.g. for transmission, I should be able to do something like `-W "http://transmission:9091;transmission.lan"`, correct? I suspect the following issues:

1. The -W parameter seems to create a 443 server only, shouldn't it listen to 80 as well?
1. The corresponding server section seems to lack a server_name, thus the default server section is used and the newly created section never gets called
1. I don't know if this is on purpose, but the locations added by -w get added to the new server block created by -W as well if calling in the order -W -w -w, which seems odd
1. There seem to be some errors in the readme corresponding to this new command, e.g. it still says `"http://<server[:port]>/;/<location>/"` which I'm guessing is a copy & paste error. I'm happy to sort these out for you once I'm sure to have understood the purpose of the new proxy_host correctly

Let me know if I'm misunderstanding the purpose, I was just getting started with this.

Cheers

**Comment by dperson** [comment]
It actually only supports sub-hosts, for example if the nginx host is `example.lan` then the sub-host would be `transmission.example.lan`, and the command line for it (modified from your example) would be: `-W "http://transmission:9091;transmission"`.

1. I really only use https (I have `-H` HSTS set), this was a first pass to make sure it seemed to work in general, and I really wouldn't want it to break / interfere with HTTPS Strict Transport Security.
2. Wow thanks, I need more sleep.
3. Doh! that wasn't intentional, thanks for the report I'll look into it.
4. I thought that I'd fixed that, and you're right it is a copy/paste error.

**Comment by dperson** [comment]
Thanks for the report. I think the issue should be fixed now.
